### ISSUE TITLE
Although I add `--debug` when running the language server, I do not see which configuration is used

### ISSUE THREAD

**Issue by sebastiaanspeck** [StevenLooman/sonar-magik#81]
https://github.com/StevenLooman/magik-tools/blob/c3b5c2cf19db626d2c497a84c1a60a866f4ef97c/magik-squid/src/main/java/nl/ramsolutions/sw/MagikToolsProperties.java#L51

I am missing this line in my language-server logging, although I have added `--debug` to the language server itself. Other debug/trace-messages are being shown.

```
2024-08-06 23:21:28 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : initialize 
2024-08-06 23:21:28 INFO    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : PID: 30604 
2024-08-06 23:21:28 INFO    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : Version: 0.10.0 
2024-08-06 23:21:28 FINE    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : Workspace folder: nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceFolder@67abf5f3(file:///c%3A/Users/sspeck, workspace) 
2024-08-06 23:21:28 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : initialized 
2024-08-06 23:21:29 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : didOpen, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,052 check: FileNotInLoadListCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: SimplifyIfCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: LocalImportProcedureCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: FileMethodCountCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,006 check: ForbiddenGlobalUsageCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: SwMethodDocCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: UseValueCompareCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,025 check: DuplicateMethodInFileCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,001 check: EmptyBlockCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: HidesVariableCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: TrailingWhitespaceCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: ScopeCountCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: LineLengthCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: NoStatementAfterBodyExitCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: MethodLineCountCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: TodoCommentCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,001 check: WarnedCallCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,001 check: UndefinedVariableCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: ExemplarSlotCountCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: LhsRhsComparatorEqualCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: VariableDeclarationUsageDistanceCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,001 check: ForbiddenCallCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: UnusedVariableCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: MethodComplexityCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: SyntaxErrorCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: UnsafeEvaluateInvocationCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: SizeZeroEmptyCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,003 check: FormattingCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: NoSelfUseCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: VariableNamingCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: TypeDocCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: VariableCountCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: ImportMissingDefinitionCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: ParameterCountCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,006 check: CommentedCodeCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.diagnostics.MagikChecksDiagnosticsProviderDuration : Duration: 0,000 check: ForbiddenInheritanceCheck, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentServiceDuration : Duration: 0,287 didOpen, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : documentSymbol, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentServiceDuration : Duration: 0,003 documentSymbol, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-06 23:21:29 WARNING org.eclipse.lsp4j.jsonrpc.RemoteEndpoint : Unmatched cancel notification for request id 2 
2024-08-06 23:21:29 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : documentSymbol, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentServiceDuration : Duration: 0,001 documentSymbol, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-06 23:21:29 WARNING org.eclipse.lsp4j.jsonrpc.RemoteEndpoint : Unmatched cancel notification for request id 4 
2024-08-06 23:21:29 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : documentSymbol, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentServiceDuration : Duration: 0,001 documentSymbol, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentServiceDuration : Duration: 0,026 codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentServiceDuration : Duration: 0,028 codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-06 23:21:29 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentServiceDuration : Duration: 0,038 codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
```

**Comment by StevenLooman** [comment]
I think this your client (emacs/[lsp-mode](https://github.com/emacs-lsp/lsp-mode)?) isn't sending the [didChangeConfiguration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration) event. Hence, the server never receives the configuration and uses the default config.

VSCode automatically sends the configuration to the server after the [initialized](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialized) event.

I do see the [configuration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) request which states:

> This pull model replaces the old push model were the client signaled configuration change via an event.

For now I would suggest the work-around to let emacs/lsp-mode send the `didChangeConfiguration` event.

**Comment by sebastiaanspeck** [comment]
> I think this your client (emacs/[lsp-mode](https://github.com/emacs-lsp/lsp-mode)?) isn't sending the [didChangeConfiguration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration) event. Hence, the server never receives the configuration and uses the default config.
> 
> VSCode automatically sends the configuration to the server after the [initialized](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialized) event.
> 
> I do see the [configuration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) request which states:
> 
> > This pull model replaces the old push model were the client signaled configuration change via an event.
> 
> For now I would suggest the work-around to let emacs/lsp-mode send the `didChangeConfiguration` event.

It worked okay with V0.9.1:
```
2024-08-08 14:56:30 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:30 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:30 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer initialize : initialize 
2024-08-08 14:56:30 INFO    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer initialize : PID: 35204 
2024-08-08 14:56:30 INFO    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer initialize : Version: 0.9.1 
2024-08-08 14:56:30 FINE    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer lambda$initialize$0 : Workspace folder: WorkspaceFolder [
  uri = "file:///c%3A/Users/sspeck"
  name = null
] 
2024-08-08 14:56:30 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer initialized : initialized 
2024-08-08 14:56:30 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService didOpen : didOpen, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-08 14:56:30 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:30 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService publishDiagnostics : Published diagnostics: 0 
2024-08-08 14:56:31 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService documentSymbol : documentSymbol, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-08 14:56:31 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService codeAction : codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-08 14:56:31 WARNING org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation : Unmatched cancel notification for request id 2 
2024-08-08 14:56:31 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService documentSymbol : documentSymbol, uri: file:///c%3A/Users/sspeck/startup.magik 
2024-08-08 14:56:31 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService codeAction : codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-08 14:56:31 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:31 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:31 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:31 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:31 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService codeAction : codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-08 14:56:31 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:31 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:32 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService codeAction : codeAction, uri: file:///c%3A/Users/sspeck/startup.magik, range: 0,0-0,0 
2024-08-08 14:56:32 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
2024-08-08 14:56:32 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService hover : hover: uri: file:///c%3A/Users/sspeck/startup.magik, position: 0,0 
2024-08-08 14:56:32 FINE    nl.ramsolutions.sw.MagikToolsProperties <init> : Read default configuration from: magik-tools-defaults.properties 
```

**Comment by StevenLooman** [comment]
I don't see any line with `Reading configuration from:` in the logging you provided.

**Comment by sebastiaanspeck** [comment]
> I don't see any line with `Reading configuration from:` in the logging you provided.

At least it showed "Read default configuration" 😄

**Comment by StevenLooman** [comment]
With https://github.com/StevenLooman/magik-tools/commit/19fc6f1c4849d028fee19157b37094ae05e91bad properties handling was rewritten. Usage of a default file was removed, and with that the logged line you are looking for.

Perhaps with this, and the missing `didChangeConfiguration`, you end up with different defaults. Although I do think I have encoded most defaults in the source itself.

**Comment by sebastiaanspeck** [comment]
With a change to the [`emacs/lsp-mode` for `lsp-magik`](https://github.com/emacs-lsp/lsp-mode/pull/4525), I was able to retrieve the didChangeConfiguration again:

```
2024-08-08 22:51:43 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : initialize 
2024-08-08 22:51:43 INFO    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : PID: 88716 
2024-08-08 22:51:43 INFO    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : Version: 0.11.0-SNAPSHOT 
2024-08-08 22:51:43 FINE    nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : Workspace folder: nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceFolder@fda8da7(file:///c%3A/Users/sebastiaan.speck, workspace) 
2024-08-08 22:51:43 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikLanguageServer : initialized 
2024-08-08 22:51:43 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : didChangeConfiguration 
2024-08-08 22:51:43 FINE    nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : New properties: {magik.typing.indexConditionUsages=true, magik.lint.overrideConfigFile=c:/Users/sebastiaan.speck/AppData/Roaming/.emacs.d/magik-lint/magik-lint.properties, magik.typing.indexGlobalUsages=true, magik.typing.cacheIndexedDefinitions=true, magik.productDirs=, magik.typing.indexSlotUsages=true, magik.typing.typeDatabasePaths=c:/Users/sebastiaan.speck/AppData/Roaming/.emacs.d/magik-lsp/types.jsonl} 
2024-08-08 22:51:43 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : Run background indexer 
2024-08-08 22:51:44 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : Start indexing workspace 
2024-08-08 22:51:44 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : didOpen, uri: file:///c%3A/Users/sebastiaan.speck/startup.magik 
2024-08-08 22:51:44 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : Run indexers 
2024-08-08 22:51:44 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : Reading type databases from: [c:/Users/sebastiaan.speck/AppData/Roaming/.emacs.d/magik-lsp/types.jsonl] 
2024-08-08 22:51:44 FINE    nl.ramsolutions.sw.magik.analysis.definitions.io.JsonDefinitionReader : Reading type database from path: c:\Users\sebastiaan.speck\AppData\Roaming\.emacs.d\magik-lsp\types.jsonl 
2024-08-08 22:51:45 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : documentSymbol, uri: file:///c%3A/Users/sebastiaan.speck/startup.magik 
2024-08-08 22:51:45 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : codeAction, uri: file:///c%3A/Users/sebastiaan.speck/startup.magik, range: 0,0-0,0 
2024-08-08 22:51:45 WARNING org.eclipse.lsp4j.jsonrpc.RemoteEndpoint : Unmatched cancel notification for request id 2 
2024-08-08 22:51:45 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : documentSymbol, uri: file:///c%3A/Users/sebastiaan.speck/startup.magik 
2024-08-08 22:51:45 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : codeAction, uri: file:///c%3A/Users/sebastiaan.speck/startup.magik, range: 0,0-0,0 
2024-08-08 22:51:45 WARNING org.eclipse.lsp4j.jsonrpc.RemoteEndpoint : Unmatched cancel notification for request id 4 
2024-08-08 22:51:45 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : documentSymbol, uri: file:///c%3A/Users/sebastiaan.speck/startup.magik 
2024-08-08 22:51:45 FINE    nl.ramsolutions.sw.magik.languageserver.MagikTextDocumentService : codeAction, uri: file:///c%3A/Users/sebastiaan.speck/startup.magik, range: 0,0-0,0 
2024-08-08 22:52:15 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : Reading docs from product dirs: [] 
2024-08-08 22:52:15 FINE    nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceFolder : On init: nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceFolder@fda8da7(file:///c%3A/Users/sebastiaan.speck, workspace) 
2024-08-08 22:52:15 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceFolder : Running IgnoreHandler for: nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceFolder@fda8da7(file:///c%3A/Users/sebastiaan.speck, workspace) 
2024-08-08 22:52:15 FINE    nl.ramsolutions.sw.IgnoreHandler : Handling file event: nl.ramsolutions.sw.magik.FileEvent@cc6fc990(file:///c%3A/Users/sebastiaan.speck, CREATED) 
2024-08-08 22:52:16 SEVERE  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : java.nio.file.AccessDeniedException: c:\Users\sebastiaan.speck\AppData\Local\Application Data 
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: c:\Users\sebastiaan.speck\AppData\Local\Application Data
	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
	at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at nl.ramsolutions.sw.IgnoreHandler.handleFileEvent(IgnoreHandler.java:51)
	at nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceFolder.runIgnoreHandler(MagikWorkspaceFolder.java:108)
	at nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceFolder.onInit(MagikWorkspaceFolder.java:77)
	at nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService.runIndexers(MagikWorkspaceService.java:247)
	at nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService.lambda$runIndexersInBackground$5(MagikWorkspaceService.java:277)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.nio.file.AccessDeniedException: c:\Users\sebastiaan.speck\AppData\Local\Application Data
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:535)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:301)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:94)
	... 21 more

2024-08-08 22:52:16 FINEST  nl.ramsolutions.sw.magik.languageserver.MagikWorkspaceService : Done indexing workspace in background 
```

As you can see, it reads my own type database, but I can't see the logging that it is using my `overrideConfigFile`.
When changing something in my `magik-lint.properties` and letting the `languageServer` run the checks again, did change the output of the issues.

As the issue seems resolved now, it would still be a good thing to at least see which properties-path we are using, right?

**Comment by StevenLooman** [comment]
I wouldn't recommend using your whole userprofile as the workspace. 😆 

The properties are now (or at least should be) mixed. I.e., the settings provided by the language client (emacs/lsp-mode in your case) are overridden with the relevant `magik-lint.properties`. You are right when you say that the filename `magik-lint.properties` is a bit confusing, but I'd rather not break existing code bases which rely on this.

Showing the path is certainly possible. I'll add it soon.

**Comment by sebastiaanspeck** [comment]
> I wouldn't recommend using your whole userprofile as the workspace. 😆

I know, minor issue on my side.

> The properties are now (or at least should be) mixed. I.e., the settings provided by the language client (emacs/lsp-mode in your case) are overridden with the relevant `magik-lint.properties`. You are right when you say that the filename `magik-lint.properties` is a bit confusing, but I'd rather not break existing code bases which rely on this.

IMO the file itself does not need to be renamed.

> Showing the path is certainly possible. I'll add it soon.

Great! If that is added, this issue can be closed.

**Comment by StevenLooman** [comment]
Should be fixed in: https://github.com/StevenLooman/magik-tools/commit/180c931d8375c3d2aa5e85939da9c07be241d90e. Please validate.

**Comment by sebastiaanspeck** [comment]
> Should be fixed in: https://github.com/StevenLooman/magik-tools/commit/180c931d8375c3d2aa5e85939da9c07be241d90e. Please validate.

Validated!

```
2024-08-09 23:30:00 FINE    nl.ramsolutions.sw.ConfigurationReader : Reading properties from: c:\Users\sebastiaan.speck\AppData\Roaming\.emacs.d\magik-lint\magik-lint.properties 
2024-08-09 23:30:00 FINE    nl.ramsolutions.sw.ConfigurationReader : Reading properties from: c:\Users\sebastiaan.speck\AppData\Roaming\.emacs.d\magik-lint\magik-lint.properties 
2024-08-09 23:30:00 FINE    nl.ramsolutions.sw.ConfigurationReader : Reading properties from: c:\Users\sebastiaan.speck\AppData\Roaming\.emacs.d\magik-lint\magik-lint.properties 
2024-08-09 23:30:00 FINE    nl.ramsolutions.sw.ConfigurationReader : Reading properties from: c:\Users\sebastiaan.speck\AppData\Roaming\.emacs.d\magik-lint\magik-lint.properties 
2024-08-09 23:30:00 FINE    nl.ramsolutions.sw.ConfigurationReader : Reading properties from: c:\Users\sebastiaan.speck\AppData\Roaming\.emacs.d\magik-lint\magik-lint.properties 
2024-08-09 23:30:00 FINE    nl.ramsolutions.sw.ConfigurationReader : Reading properties from: c:\Users\sebastiaan.speck\AppData\Roaming\.emacs.d\magik-lint\magik-lint.properties 
2024-08-09 23:30:00 FINE    nl.ramsolutions.sw.ConfigurationReader : Reading properties from: c:\Users\sebastiaan.speck\AppData\Roaming\.emacs.d\magik-lint\magik-lint.properties 
```

Maybe a little improvement to not load the configuration 7 times after each other? But that is out of scope for this issue. The issue itself is fixed.
